<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('languages')->insert([

            ["code" => "en", "name" => "English", "nativeName" => "English", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["code" => "ar", "name" => "Arabic", "nativeName" => "العربية", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["code" => "bn", "name" => "Bengali", "nativeName" => "বাংলা", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["code" => "ab", "name" => "Abkhaz", "nativeName" => "аҧсуа", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "aa", "name" => "Afar", "nativeName" => "Afaraf", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "af", "name" => "Afrikaans", "nativeName" => "Afrikaans", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ak", "name" => "Akan", "nativeName" => "Akan", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sq", "name" => "Albanian", "nativeName" => "Shqip", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "am", "name" => "Amharic", "nativeName" => "አማርኛ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "an", "name" => "Aragonese", "nativeName" => "Aragonés", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "hy", "name" => "Armenian", "nativeName" => "Հայերեն", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "as", "name" => "Assamese", "nativeName" => "অসমীয়া", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "av", "name" => "Avaric", "nativeName" => "авар мацӀ, магӀарул мацӀ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ae", "name" => "Avestan", "nativeName" => "avesta", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ay", "name" => "Aymara", "nativeName" => "aymar aru", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "az", "name" => "Azerbaijani", "nativeName" => "azərbaycan dili", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "bm", "name" => "Bambara", "nativeName" => "bamanankan", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ba", "name" => "Bashkir", "nativeName" => "башҡорт теле", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "eu", "name" => "Basque", "nativeName" => "euskara, euskera", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "be", "name" => "Belarusian", "nativeName" => "Беларуская", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "bh", "name" => "Bihari", "nativeName" => "भोजपुरी", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "bi", "name" => "Bislama", "nativeName" => "Bislama", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "bs", "name" => "Bosnian", "nativeName" => "bosanski jezik", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "br", "name" => "Breton", "nativeName" => "brezhoneg", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "bg", "name" => "Bulgarian", "nativeName" => "български език", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "my", "name" => "Burmese", "nativeName" => "ဗမာစာ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ca", "name" => "Catalan; Valencian", "nativeName" => "Català", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ch", "name" => "Chamorro", "nativeName" => "Chamoru", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ce", "name" => "Chechen", "nativeName" => "нохчийн мотт", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ny", "name" => "Chichewa; Chewa; Nyanja", "nativeName" => "chiCheŵa, chinyanja", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "zh", "name" => "Chinese", "nativeName" => "中文 (Zhōngwén), 汉语, 漢語", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "cv", "name" => "Chuvash", "nativeName" => "чӑваш чӗлхи", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "kw", "name" => "Cornish", "nativeName" => "Kernewek", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "co", "name" => "Corsican", "nativeName" => "corsu, lingua corsa", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "cr", "name" => "Cree", "nativeName" => "ᓀᐦᐃᔭᐍᐏᐣ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "hr", "name" => "Croatian", "nativeName" => "hrvatski", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "cs", "name" => "Czech", "nativeName" => "česky, čeština", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "da", "name" => "Danish", "nativeName" => "dansk", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "dv", "name" => "Divehi; Dhivehi; Maldivian;", "nativeName" => "ދިވެހި", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "nl", "name" => "Dutch", "nativeName" => "Nederlands, Vlaams", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "eo", "name" => "Esperanto", "nativeName" => "Esperanto", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "et", "name" => "Estonian", "nativeName" => "eesti, eesti keel", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ee", "name" => "Ewe", "nativeName" => "Eʋegbe", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "fo", "name" => "Faroese", "nativeName" => "føroyskt", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "fj", "name" => "Fijian", "nativeName" => "vosa Vakaviti", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "fi", "name" => "Finnish", "nativeName" => "suomi, suomen kieli", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "fr", "name" => "French", "nativeName" => "français, langue française", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ff", "name" => "Fula; Fulah; Pulaar; Pular", "nativeName" => "Fulfulde, Pulaar, Pular", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "gl", "name" => "Galician", "nativeName" => "Galego", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ka", "name" => "Georgian", "nativeName" => "ქართული", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "de", "name" => "German", "nativeName" => "Deutsch", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "el", "name" => "Greek, Modern", "nativeName" => "Ελληνικά", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "gn", "name" => "Guaraní", "nativeName" => "Avañeẽ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "gu", "name" => "Gujarati", "nativeName" => "ગુજરાતી", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ht", "name" => "Haitian; Haitian Creole", "nativeName" => "Kreyòl ayisyen", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ha", "name" => "Hausa", "nativeName" => "Hausa, هَوُسَ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "he", "name" => "Hebrew (modern)", "nativeName" => "עברית", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "hz", "name" => "Herero", "nativeName" => "Otjiherero", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "hi", "name" => "Hindi", "nativeName" => "हिन्दी, हिंदी", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ho", "name" => "Hiri Motu", "nativeName" => "Hiri Motu", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "hu", "name" => "Hungarian", "nativeName" => "Magyar", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ia", "name" => "Interlingua", "nativeName" => "Interlingua", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "id", "name" => "Indonesian", "nativeName" => "Bahasa Indonesia", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ie", "name" => "Interlingue", "nativeName" => "Originally called Occidental; then Interlingue after WWII", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ga", "name" => "Irish", "nativeName" => "Gaeilge", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ig", "name" => "Igbo", "nativeName" => "Asụsụ Igbo", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ik", "name" => "Inupiaq", "nativeName" => "Iñupiaq, Iñupiatun", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "io", "name" => "Ido", "nativeName" => "Ido", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "is", "name" => "Icelandic", "nativeName" => "Íslenska", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "it", "name" => "Italian", "nativeName" => "Italiano", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "iu", "name" => "Inuktitut", "nativeName" => "ᐃᓄᒃᑎᑐᑦ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ja", "name" => "Japanese", "nativeName" => "日本語 (にほんご／にっぽんご)", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "jv", "name" => "Javanese", "nativeName" => "basa Jawa", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "kl", "name" => "Kalaallisut, Greenlandic", "nativeName" => "kalaallisut, kalaallit oqaasii", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "kn", "name" => "Kannada", "nativeName" => "ಕನ್ನಡ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "kr", "name" => "Kanuri", "nativeName" => "Kanuri", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ks", "name" => "Kashmiri", "nativeName" => "कश्मीरी, كشميري‎", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "kk", "name" => "Kazakh", "nativeName" => "Қазақ тілі", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "km", "name" => "Khmer", "nativeName" => "ភាសាខ្មែរ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ki", "name" => "Kikuyu, Gikuyu", "nativeName" => "Gĩkũyũ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "rw", "name" => "Kinyarwanda", "nativeName" => "Ikinyarwanda", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ky", "name" => "Kirghiz, Kyrgyz", "nativeName" => "кыргыз тили", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "kv", "name" => "Komi", "nativeName" => "коми кыв", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "kg", "name" => "Kongo", "nativeName" => "KiKongo", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ko", "name" => "Korean", "nativeName" => "한국어 (韓國語), 조선말 (朝鮮語)", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ku", "name" => "Kurdish", "nativeName" => "Kurdî, كوردی‎", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "kj", "name" => "Kwanyama, Kuanyama", "nativeName" => "Kuanyama", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "la", "name" => "Latin", "nativeName" => "latine, lingua latina", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "lb", "name" => "Luxembourgish, Letzeburgesch", "nativeName" => "Lëtzebuergesch", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "lg", "name" => "Luganda", "nativeName" => "Luganda", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "li", "name" => "Limburgish, Limburgan, Limburger", "nativeName" => "Limburgs", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ln", "name" => "Lingala", "nativeName" => "Lingála", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "lo", "name" => "Lao", "nativeName" => "ພາສາລາວ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "lt", "name" => "Lithuanian", "nativeName" => "lietuvių kalba", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "lu", "name" => "Luba-Katanga", "nativeName" => "", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "lv", "name" => "Latvian", "nativeName" => "latviešu valoda", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "gv", "name" => "Manx", "nativeName" => "Gaelg, Gailck", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "mk", "name" => "Macedonian", "nativeName" => "македонски јазик", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "mg", "name" => "Malagasy", "nativeName" => "Malagasy fiteny", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ms", "name" => "Malay", "nativeName" => "bahasa Melayu, بهاس ملايو‎", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ml", "name" => "Malayalam", "nativeName" => "മലയാളം", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "mt", "name" => "Maltese", "nativeName" => "Malti", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "mi", "name" => "Māori", "nativeName" => "te reo Māori", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "mr", "name" => "Marathi (Marāṭhī)", "nativeName" => "मराठी", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "mh", "name" => "Marshallese", "nativeName" => "Kajin M̧ajeļ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "mn", "name" => "Mongolian", "nativeName" => "монгол", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "na", "name" => "Nauru", "nativeName" => "Ekakairũ Naoero", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "nv", "name" => "Navajo, Navaho", "nativeName" => "Diné bizaad, Dinékʼehǰí", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "nb", "name" => "Norwegian Bokmål", "nativeName" => "Norsk bokmål", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "nd", "name" => "North Ndebele", "nativeName" => "isiNdebele", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ne", "name" => "Nepali", "nativeName" => "नेपाली", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ng", "name" => "Ndonga", "nativeName" => "Owambo", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "nn", "name" => "Norwegian Nynorsk", "nativeName" => "Norsk nynorsk", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "no", "name" => "Norwegian", "nativeName" => "Norsk", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ii", "name" => "Nuosu", "nativeName" => "ꆈꌠ꒿ Nuosuhxop", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "nr", "name" => "South Ndebele", "nativeName" => "isiNdebele", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "oc", "name" => "Occitan", "nativeName" => "Occitan", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "oj", "name" => "Ojibwe, Ojibwa", "nativeName" => "ᐊᓂᔑᓈᐯᒧᐎᓐ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "cu", "name" => "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic", "nativeName" => "ѩзыкъ словѣньскъ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "om", "name" => "Oromo", "nativeName" => "Afaan Oromoo", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "or", "name" => "Oriya", "nativeName" => "ଓଡ଼ିଆ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "os", "name" => "Ossetian, Ossetic", "nativeName" => "ирон æвзаг", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "pa", "name" => "Panjabi, Punjabi", "nativeName" => "ਪੰਜਾਬੀ, پنجابی‎", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "pi", "name" => "Pāli", "nativeName" => "पाऴि", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "fa", "name" => "Persian", "nativeName" => "فارسی", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "pl", "name" => "Polish", "nativeName" => "polski", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ps", "name" => "Pashto, Pushto", "nativeName" => "پښتو", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "pt", "name" => "Portuguese", "nativeName" => "Português", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "qu", "name" => "Quechua", "nativeName" => "Runa Simi, Kichwa", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "rm", "name" => "Romansh", "nativeName" => "rumantsch grischun", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "rn", "name" => "Kirundi", "nativeName" => "kiRundi", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ro", "name" => "Romanian, Moldavian, Moldovan", "nativeName" => "română", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ru", "name" => "Russian", "nativeName" => "русский язык", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sa", "name" => "Sanskrit (Saṁskṛta)", "nativeName" => "संस्कृतम्", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sc", "name" => "Sardinian", "nativeName" => "sardu", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sd", "name" => "Sindhi", "nativeName" => "सिन्धी, سنڌي، سندھی‎", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "se", "name" => "Northern Sami", "nativeName" => "Davvisámegiella", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sm", "name" => "Samoan", "nativeName" => "gagana faa Samoa", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sg", "name" => "Sango", "nativeName" => "yângâ tî sängö", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sr", "name" => "Serbian", "nativeName" => "српски језик", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "gd", "name" => "Scottish Gaelic; Gaelic", "nativeName" => "Gàidhlig", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sn", "name" => "Shona", "nativeName" => "chiShona", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "si", "name" => "Sinhala, Sinhalese", "nativeName" => "සිංහල", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sk", "name" => "Slovak", "nativeName" => "slovenčina", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sl", "name" => "Slovene", "nativeName" => "slovenščina", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "so", "name" => "Somali", "nativeName" => "Soomaaliga, af Soomaali", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "st", "name" => "Southern Sotho", "nativeName" => "Sesotho", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "es", "name" => "Spanish; Castilian", "nativeName" => "español, castellano", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "su", "name" => "Sundanese", "nativeName" => "Basa Sunda", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sw", "name" => "Swahili", "nativeName" => "Kiswahili", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ss", "name" => "Swati", "nativeName" => "SiSwati", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "sv", "name" => "Swedish", "nativeName" => "svenska", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ta", "name" => "Tamil", "nativeName" => "தமிழ்", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "te", "name" => "Telugu", "nativeName" => "తెలుగు", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "tg", "name" => "Tajik", "nativeName" => "тоҷикӣ, toğikī, تاجیکی‎", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "th", "name" => "Thai", "nativeName" => "ไทย", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ti", "name" => "Tigrinya", "nativeName" => "ትግርኛ", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "bo", "name" => "Tibetan Standard, Tibetan, Central", "nativeName" => "བོད་ཡིག", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "tk", "name" => "Turkmen", "nativeName" => "Türkmen, Түркмен", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "tl", "name" => "Tagalog", "nativeName" => "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "tn", "name" => "Tswana", "nativeName" => "Setswana", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "to", "name" => "Tonga (Tonga Islands)", "nativeName" => "faka Tonga", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "tr", "name" => "Turkish", "nativeName" => "Türkçe", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ts", "name" => "Tsonga", "nativeName" => "Xitsonga", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "tt", "name" => "Tatar", "nativeName" => "татарча, tatarça, تاتارچا‎", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "tw", "name" => "Twi", "nativeName" => "Twi", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ty", "name" => "Tahitian", "nativeName" => "Reo Tahiti", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ug", "name" => "Uighur, Uyghur", "nativeName" => "Uyƣurqə, ئۇيغۇرچە‎", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "uk", "name" => "Ukrainian", "nativeName" => "українська", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ur", "name" => "Urdu", "nativeName" => "اردو", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "uz", "name" => "Uzbek", "nativeName" => "zbek, Ўзбек, أۇزبېك‎", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "ve", "name" => "Venda", "nativeName" => "Tshivenḓa", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "vi", "name" => "Vietnamese", "nativeName" => "Tiếng Việt", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "vo", "name" => "Volapük", "nativeName" => "Volapük", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "wa", "name" => "Walloon", "nativeName" => "Walon", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "cy", "name" => "Welsh", "nativeName" => "Cymraeg", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "wo", "name" => "Wolof", "nativeName" => "Wollof", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "fy", "name" => "Western Frisian", "nativeName" => "Frysk", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "xh", "name" => "Xhosa", "nativeName" => "isiXhosa", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "yi", "name" => "Yiddish", "nativeName" => "ייִדיש", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "yo", "name" => "Yoruba", "nativeName" => "Yorùbá", "status" => 0, "created_at" => now(), "updated_at" => now()],
            ["code" => "za", "name" => "Zhuang, Chuang", "nativeName" => "Saɯ cueŋƅ, Saw cuengh", "status" => 0, "created_at" => now(), "updated_at" => now()]

        ]);
    }
}
